### ISSUE TITLE
Access form data and file data

### ISSUE THREAD

**Issue by csaf4370** [fengsp/pencil#24]
Hi,

thanks for your awesome framework, however i got a question / issue:

How is it possible to access form() data in a request and files() from the request. as both are returning a reference to a multidict: small example:

`fn post_img( r: &mut Request) -> PencilResult {
    let mut formvalues = BTreeMap::new();
    {
        let f = r.form();
        for i in f.keys() {
            formvalues.insert(i, f.get(i));
        }
    }

    let file = r.files();
    for i in file.getlist("data") {
        for j in i {
            let mut ff = File::open(j.path.clone()).unwrap();
            let mut contents: Vec<u8> = Vec::new();
            let data = ff.read_to_end(&mut contents).unwrap();

            let mut fff = File::create("/home/marcom/test.jpg").unwrap();
            fff.write_all(&contents).unwrap();
        }
    }
    let mut d = BTreeMap::new();
    d.insert("status", "ok");
    return jsonify(&d);
}

fn main() {
    let mut app = Pencil::new("/web/hello");
    app.route("/post_img", &[Post], "post_img", post_img);
    app.run("127.0.0.1:9998");
}`

here the compiler complains with the following message:

> src/main.rs:73:16: 73:17 error: cannot borrow `*r` as mutable more than once at a time [E0499]
src/main.rs:73     let file = r.files();
                              ^
src/main.rs:73:16: 73:17 help: run `rustc --explain E0499` to see a detailed explanation
src/main.rs:67:17: 67:18 note: previous borrow of `*r` occurs here; the mutable borrow prevents subsequent moves, borrows, or modification of `*r` until the borrow ends
src/main.rs:67         let f = r.form();
                               ^
src/main.rs:87:2: 87:2 note: previous borrow ends here
src/main.rs:64 fn post_img( r: &mut Request) -> PencilResult {
               ...
src/main.rs:87 }

Cheers

**Comment by csaf4370** [comment]
by cloning the form data i was able to resolve it. Is this the right way to do?

`fn post_img( r: &mut Request) -> PencilResult {
    let f = r.form().clone();
    let mut formvalues = BTreeMap::new();

    for i in f.keys() {
        formvalues.insert(i, f.get(i));
    }
    println!("{:?}", formvalues);

    let file = r.files();
    for i in file.getlist("data") {
        for j in i {
            let mut ff = File::open(j.path.clone()).unwrap();
            let mut contents: Vec<u8> = Vec::new();
            let data = ff.read_to_end(&mut contents).unwrap();

            let mut fff = File::create("/home/marcom/test.jpg").unwrap();
            fff.write_all(&contents).unwrap();
        }
    }
    let mut d = BTreeMap::new();
    d.insert("status", "ok");
    return jsonify(&d);
}`

**Comment by fengsp** [comment]
Maybe you can just move the temporary file to the destination.

**Comment by csaf4370** [comment]
thanks @fengsp that would maybe a better option... but the question is
if I can use the form values and the files-values without cloning, as both methods:
request.form and request.files are methods with '&mut self' parameter and returning a reference to the multidict. 

the removal of the 'mut' in 'fn form(&mut self)' and the files fn would allow the usage of all fields without clone()

**Comment by fengsp** [comment]
Currently you need to clone it if you need it later, in your example, you can use `scope` to avoid it.  Maybe in the future we will add a method that allows you to consume the form data.

**Comment by csaf4370** [comment]
Ok, thanks for the clarification. 

Keep up the good work ;) ... will close this issue now.
