### ISSUE TITLE
Equivalent of Flask.g

### ISSUE THREAD

**Issue by Xion** [fengsp/pencil#9]
Flask offers a request-local grabbag of stuff in the form of `g` variable. Pencil could use something like that pretty badly. The main application right now would be to store the database connection objects, because existing ORM frameworks (e.g. Diesel) do not offer their own solutions for that in the vein of SQLAlchemy's `scoped_session`.

**Comment by justinas** [comment]
Iron solves this by having a [TypeMap attribute](https://github.com/iron/iron/blob/ed0b849656189365e2b6241708c85c2b1a824f68/src/request/mod.rs#L48) in the Request struct. This way you can associate anything with the current request without having to rely on any global instances.

**Comment by fengsp** [comment]
@justinas We have that too.

**Comment by justinas** [comment]
Oops, completely missed that. I wonder if that solves @Xion's use case or
if there's a particular need not fulfilled by TypeMap.

**Comment by fengsp** [comment]
For now we could just use the `TypeMap` until there is a better solution.
